//
// Created by fabian on 28.05.21.
//

#ifndef TESSLA_CUDA_DEVICE_INFORMATION_CUH
#define TESSLA_CUDA_DEVICE_INFORMATION_CUH

#define WARP_SIZE 32
#define MAX_THREADS_PER_BLOCK 1024
#define MAX_BLOCKS 1024
#endif //TESSLA_CUDA_DEVICE_INFORMATION_CUH
